import { Benefits } from "~/components/Benefits";
import { ContactForm } from "~/components/ContactForm";
import { ContactUs } from "~/components/ContactUs";
import { Discover } from "~/components/Discover";
import { Header } from "~/components/Header";
import { Hero } from "~/components/Hero";
import { HowItWorks } from "~/components/HowItWorks";
import { Solutions } from "~/components/Solutions";
import { Unique } from "~/components/Unique";
import { Vehicles } from "~/components/Vehicles";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Kolors clone for educational purposes</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <Unique />
      <HowItWorks />
      <Benefits />
      <ContactForm />
      <ContactUs />
      <Vehicles />
      <Solutions />
      <Discover />
    </>
  );
}
